### ISSUE TITLE
Update virtualbox image in the mirror

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/vagrant-openshift#250]
The current image [fedora_virtualbox_inst.box](https://mirror.openshift.com/pub/vagrant/boxes/openshift3/fedora_virtualbox_inst.box) is dated 2015-04-06 16:15, and therefore do not include this change https://github.com/openshift/vagrant-openshift/commit/450d1d5d4de6806e3feb0a962a1f1bb3137de9f3, which affects people getting started with OpenShift (that need to manually change `/etc/sysconfig/docker`).

Could we have a fresh image uploaded to the mirror?
(The same might apply for providers other than VirtualBox, but I haven't used them)

@danmcp @smarterclayton

**Comment by danmcp** [comment]
@rhcarvalho It will be updated once we get through all the Docker 1.6 upgrade issues.
