### ISSUE TITLE
"Cannot hard link" tar errors during sync-openshift

### ISSUE THREAD

**Issue by adellape** [openshift/vagrant-openshift#345]
Are the following steps still the recommended flow?

https://github.com/openshift/vagrant-openshift#initialize-local-vagrant-conf

Basically, `vagrant origin-init` -> `vagrant up` -> `vagrant sync-openshift` (I notice it was just updated to `sync-origin` today, but I'm using the gem version so it's still `sync-openshift` atm). It used to work fine, but I've been getting the following errors lately during the `sync-openshift` step:

```
...
hack/build-images.sh took 628 seconds
hack/extract-release.sh
Makefile:169: recipe for target 'release' failed


Stderr from the command:

tar: ./openshift: Cannot hard link to ‘./kube-scheduler’: Operation not permitted
tar: ./oc: Cannot hard link to ‘./kubectl’: Operation not permitted
tar: ./kube-proxy: Cannot hard link to ‘./kube-scheduler’: Operation not permitted
tar: ./oadm: Cannot hard link to ‘./kube-scheduler’: Operation not permitted
tar: ./kube-controller-manager: Cannot hard link to ‘./kube-scheduler’: Operation not permitted
tar: ./kubelet: Cannot hard link to ‘./kube-scheduler’: Operation not permitted
tar: ./kube-apiserver: Cannot hard link to ‘./kube-scheduler’: Operation not permitted
tar: Exiting with failure status due to previous errors
make: *** [release] Error 2
```

This is after vagrant halt/destroying all VMs, updating origin repo and vagrant plugin (gem) to latest, etc. Host OS is Fedora 22, using Virtual Box as provider. Running the `sync-openshift` as non-root, no sudo. Here's the vagrant-openshift version and `.vagrant-openshift.json` file:

```
$ vagrant plugin list
vagrant-openshift (2.0.10)
vagrant-share (1.1.4, system)

$ cat .vagrant-openshift.json {
  "instance_name": "test3",
  "os": "fedora",
  "dev_cluster": false,
  "insert_key": true,
  "num_minions": 2,
  "cpus": 2,
  "memory": 2048,
  "rebuild_yum_cache": false,
  "instance_type": "t2.medium",
  "volume_size": 25,
  "no_synced_folders": false,
  "sync_to": "/data/src",
  "sync_from": "/home/durant/go/src",
  "virtualbox": {
    "box_name": "fedora_inst",
    "box_url": "https://mirror.openshift.com/pub/vagrant/boxes/openshift3/fedora_virtualbox_inst.box"
  },
  "libvirt": {
    "box_name": "fedora_inst",
    "box_url": "https://mirror.openshift.com/pub/vagrant/boxes/openshift3/fedora_libvirt_inst.box"
  },
  "aws": {
    "ami": "<AMI_ID>",
    "ami_region": "us-east-1",
    "ssh_user": "fedora"
  },
  "openstack": {
    "image": "<Fedora>",
    "ssh_user": "fedora"
  }
```

**Comment by danmcp** [comment]
This should work.  Although it doesn't anymore.  You probably just want to run make for now.

**Comment by smarterclayton** [comment]
It's because of vboxfs not supporting hard linking, but people really wanting release TAR output from us that has hard links.  Will look into it after 3.1.

**Comment by stevekuznetsov** [comment]
Is this still a valid issue?

**Comment by adellape** [comment]
Updated the plug-in and everything else I could think of this morning and can't reproduce this issue. I get other errors (may open a separate Issue), but it's no longer this hard link problem, so I'll close this.
