### ISSUE TITLE
vagrant test-origin timing out in 4 hours

### ISSUE THREAD

**Issue by aveshagarwal** [openshift/vagrant-openshift#386]
While running origin extended tests on aws (vagrant test-origin --extended "core" --skip-check --skip-image-cleanup on f22), it is timing out every 4 hours:

```
Timeout occurred while running ssh/sudo command:
set -e
pushd /data/src/github.com/openshift//origin >/dev/null
export PATH=$GOPATH/bin:$PATH

echo '***************************************************'
echo 'Running TEST_REPORT_DIR=/tmp/openshift-extended-tests/junit/extended test/extended/core.sh...'
time TEST_REPORT_DIR=/tmp/openshift-extended-tests/junit/extended test/extended/core.sh
echo 'Finished TEST_REPORT_DIR=/tmp/openshift-extended-tests/junit/extended test/extended/core.sh'
echo '***************************************************'

popd >/dev/nul
```

I think its because timeout is hardcoded to 4 hours (60_60_4) in ./lib/vagrant-openshift/action/run_origin_tests.rb.  Could we make it configurable or increase the timeout further?

**Comment by danmcp** [comment]
@aveshagarwal I think it's time we split up the tests instead.  The four hour number is based on the instance reaping which will kick in if this doesn't.  We could increase that but I don't think the answer is to keep bumping the numbers.

**Comment by aveshagarwal** [comment]
@danmcp I agree. But having a config option to set timeout would be helpful before tests are split up.

**Comment by stevekuznetsov** [comment]
I think we've addressed this by changing the test suite structure.
