### ISSUE TITLE
`download-artifacts-origin` downloads volumes directory

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/vagrant-openshift#390]
`volumes` directory is by far the largest artifact we download. Can we blacklist all paths containing `/volumes/` from being downloaded? Will this lead to behavior that's difficult to reason about later? Do we want some of the volumes, but not all?

@deads2k @bparees @danmcp

**Comment by bparees** [comment]
i'd be ok with blacklisting it.

**Comment by deads2k** [comment]
I'm assuming this came out of https://github.com/openshift/origin/issues/6814.

I have no issue with blacklisting it.
