### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/vagrant-openshift#394]
I'm hitting this warning every time I use Docker in the VirtualBox VM (image from Monday IIRC):

```console
$ docker run --rm -it centos:7
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
[root@afbcbda53ec5 /]# 
```

~~It seems to be not just a warning but it is also preventing `docker run` and getting a bash shell.~~

@danmcp perhaps there's some configuration missing?

**Comment by mfojtik** [comment]
yeah, we should have `--storage-opt dm.no_warn_on_loop_devices=true` in `/etc/sysconfig/docker` or setup better storage for docker which will eventually improve the speed of docker builds ;-)

@danmcp any clues if somebody is looking into using LVM or something more efficient for Docker in our vagrant boxes?

**Comment by rhcarvalho** [comment]
@mfojtik do you have any workaround to get `docker run` to work?

Even after editing `/etc/sysconfig/docker` and restarting the Docker daemon, `docker run --rm centos:7` still doesn't work -- and doesn't produce any warnings.

**Comment by mfojtik** [comment]
@rhcarvalho if you want bash shell you have to run `docker run --rm -it centos:7 /bin/bash`

**Comment by mfojtik** [comment]
@rhcarvalho and you can of course omit the /bin/bash part ;-)

**Comment by rhcarvalho** [comment]
dahhh of course... where's my head today...

thanks ;)

**Comment by rhcarvalho** [comment]
Updated the description: the issue is only the warning.

(and of course my silly mind today :wink:  ...)

**Comment by danmcp** [comment]
>  @danmcp any clues if somebody is looking into using LVM or something more efficient for Docker in our vagrant boxes?

@mfojtik I don't think anyone is looking at it.  @ironcladlou did a one off image one time but it needs to get automated into vagrant-openshift.

**Comment by danmcp** [comment]
@rhcarvalho @mfojtik FYI I am taking a look at this now.

**Comment by danmcp** [comment]
@rhcarvalho @mfojtik  fedora and centos have been updated for virtualbox and libvirt

**Comment by rhcarvalho** [comment]
thanks @danmcp

**Comment by danmcp** [comment]
I went ahead and updated all the amis as well.
