### ISSUE TITLE
README should suggest `dnf install` for `vagrant-libvirt` 

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/vagrant-openshift#448]
Installing `vagrant-libvirt` using the vagrant plugin installer is a PITA due to the linker troubles linked in the README. Following all of the steps written there (and in the `vagrant-libvirt` repo) did not help my issue, but F23 ships a `vagrant-libvirt` repo, so `dnf install` is the best way by far of getting the plugin. We should suggest that route for anyone with a distro that allows it.

**Comment by coreydaley** [comment]
I second this, would have saved me a decent amount of time if this had been listed

**Comment by coreydaley** [comment]
The current README does include instructions to install vagrant-libvirt, and only run the vagrant plugin install vagrant-libvirt if the "yum|dnf install vagrant-libvirt" fails.

**Comment by stevekuznetsov** [comment]
Yeah, looks like Jim cleaned it up. Cool.
