### ISSUE TITLE
vagrant origin-local-checkout does not support --branch

### ISSUE THREAD

**Issue by smarterclayton** [openshift/vagrant-openshift#463]
The --replace path doesn't support --branch, and also it assumes that each of the local repos has the same branch (which for the use case of doing a Jenkins test should not be the case).  Specifically for test_pr_origin we don't need the other three repos, just the one.

**Comment by smarterclayton** [comment]
@danmcp

**Comment by smarterclayton** [comment]
Also ignores the --repo flag, so I can't "just" clone origin:

```
GOPATH=/tmp/test vagrant origin-local-checkout --branch release-1.3.0-alpha.2 --replace --repo origin
Waiting for the cloning process to finish
Cloning origin ...
Cloning source-to-image ...
Cloning origin-web-console ...
Origin repositories cloned into /private/tmp/test/src/github.com/openshift
```

**Comment by danmcp** [comment]
Fixed with: https://github.com/openshift/vagrant-openshift/commit/0626bfd5b9749cba0ed31904080cb8b63f7c095d
