### ISSUE TITLE
extended tests doesn't handle pipe correctly for focus

### ISSUE THREAD

**Issue by bparees** [openshift/vagrant-openshift#476]
if you specify a test like core(A|B) intending to get all tests that match either A or B, you instead get all tests that match "A|B" which is nothing.

we're mishandling the pipe.

@mfojtik @stevekuznetsov

**Comment by stevekuznetsov** [comment]
We should only need to escape double quotes in the focus string, instead of full shell words as we are doing [here](https://github.com/openshift/vagrant-openshift/blob/master/lib/vagrant-openshift/action/run_origin_tests.rb#L137)
